version: '3.4'

services:
  clinic.api:
    image: ${DOCKER_REGISTRY-}clinicapi
    build:
      context: .
      dockerfile: Clinic.API/Dockerfile

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
